packages:
  - "apps/*"
  - "packages/*"

onlyBuiltDependencies:
  - esbuild
  - msgpackr-extract
  - sharp
allowBuilds:
  esbuild: set this to true or false
  msgpackr-extract: set this to true or false
  sharp: set this to true or false
